name: Node.js Deployment

on:
  push:
    branches:
      - master

jobs:
  checkout_and_setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: '20'

  install_dependencies:
    runs-on: ubuntu-latest
    needs: checkout_and_setup
    steps:
    - name: Install npm dependencies
      run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: [checkout_and_setup, install_dependencies]
    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/nodejs-testing
          git pull origin master
          npm install --production
          pm2 restart index.js
